input {
  beats {
  port => "5044"
  }
}

  filter {
  grok {
  match => { "log_entry" => "%{DATA}%{TIMESTAMP_ISO8601:timestamp}]%{DATA} %{DATA}%{WORD:level}%{DATA} %{DATA}%{PATH:source}:%{NUMBER:line_num}%{DATA} %{GREEDYDATA:message}" }
  }
}

  output {
  elasticsearch {
  hosts => ["http://elasticsearch:9200"]
  index => "cdcf_log"
  }
  stdout { codec => rubydebug }
}