version: "3.7"
services:
  yanghui_root_v2:
    image: cdcf:latest
    environment:
      HOST: yanghui_root_v2
      ROLE: root
      SEEDS: yanghui_root_v2:4445
      LOG_COMMANDS: --log_file=/tmp/log/yanghui_root_v2.log --log_level=debug --log_file_size=2048 ${LOG_TO_CONSOLE}
      APP: /bin/yanghui_cluster_root_v2
      PRINT_PING_LOG:
      APP_ARGS: -r --root_host=yanghui_root_v2 --root_port=56600 --worker_port=56601 --threads_proportion=2 --log_file=/tmp/log/actorsystem_yanghui_root_v2.log --log_level=debug --log_file_size=2048 ${SSL_ARGS1} ${LOG_TO_CONSOLE}
    networks:
      - cdcf
    volumes:
      - /tmp/log:/tmp/log
    command: /bin/bash -c "sleep 1000000000"
  yanghui_worker1_v2:
    image: cdcf:latest
    environment:
      HOST: yanghui_worker1_v2
      ROLE: worker
      SEEDS: yanghui_root_v2:4445
      LOG_COMMANDS: --log_file=/tmp/log/yanghui_worker1_v2.log --log_level=debug --log_file_size=2048 ${LOG_TO_CONSOLE}
      APP: /bin/yanghui_cluster_root_v2
      PRINT_PING_LOG:
      APP_ARGS: --root_host=yanghui_root_v2 --root_port=56600 --worker_port=56601 --threads_proportion=2 --log_file=/tmp/log/actorsystem_yanghui_worker1_v2.log --log_level=debug --log_file_size=2048 ${SSL_ARGS2} ${LOG_TO_CONSOLE}
    networks:
      - cdcf
    volumes:
      - /tmp/log:/tmp/log
  yanghui_worker2_v2:
    image: cdcf:latest
    environment:
      HOST: yanghui_worker2_v2
      ROLE: worker
      SEEDS: yanghui_root_v2:4445
      LOG_COMMANDS: --log_file=/tmp/log/yanghui_worker2_v2.log --log_level=debug --log_file_size=2048 ${LOG_TO_CONSOLE}
      APP: /bin/yanghui_cluster_root_v2
      PRINT_PING_LOG:
      APP_ARGS: --root_host=yanghui_root_v2 -l 1 --root_port=56600 --worker_port=56601 --threads_proportion=2 --log_file=/tmp/log/actorsystem_yanghui_worker2_v2.log --log_level=debug --log_file_size=2048 ${SSL_ARGS3} ${LOG_TO_CONSOLE}
    networks:
      - cdcf
    volumes:
      - /tmp/log:/tmp/log
  yanghui_monitor:
    image: cdcf:latest
    networks:
      - cdcf
    command: /bin/bash -c "sleep 1000000000"
networks:
  cdcf:
    driver: bridge