---
- name: Stop yanghui_server container
  hosts: server
  become: true
  gather_facts: no
  tasks:
    - docker_container:
        name: yanghui_server
        state: absent
- name: Stop yanghui_worker container
  hosts: worker
  become: true
  gather_facts: no
  tasks:
    - docker_container:
        name: yanghui_worker
        state: absent
- name: Stop yanghui_client container
  hosts: client
  become: true
  gather_facts: no
  tasks:
    - docker_container:
        name: yanghui_client
        state: absent